### ISSUE TITLE
Human readable reference documentation

### ISSUE THREAD

**Issue by philipashlock** [NIEM/Implementation-Cookbook#1]
Where can I find human readable HTML versions of NIEM Core documentation?

The [3.0 release summary](http://release.niem.gov/niem/3.0/) provides links to a [spreadsheet](http://release.niem.gov/niem/3.0/niem-3.0.xlsx) and an [XSD file](http://release.niem.gov/niem/niem-core/3.0/niem-core.xsd), but no simple HTML webpage. Compared to a site like [schema.org](http://schema.org), this is very cumbersome and frustrating for quick reference. Look how simple the reference page for `givenName` is on schema.org - http://schema.org/givenName

I can't find the equivalent on the NIEM site or any .gov. The best I can find is a site like http://www.datypic.com/sc/niem30/e-nc_PersonGivenName.html

Is there an XSLT to transform the XSD to HTML?

**Comment by philipashlock** [comment]
@CB2, @webb, @jbylsma, @walmsleyph

Would it be better to post this to https://github.com/NIEM/NIEM.github.io/issues or is there somewhere else you would suggest where it might get a response?

**Comment by remybernard** [comment]
Hi Philip,
The NIEM Wayfarer is close to being an HTML browser of the model: http://niemwayfarer.org

You can search for data components and see what sub-elements are contained in the result. However, the current version of NIEM Wayfarer supports NIEM 2.1 only, not NIEM 3.0 yet. For NIEM 3.0, the SSGT tool is better (though you can't search for expressions like "city name", it has to be more specific): http://tools.niem.gov/niemtools/ssgt/index.iepd

**Comment by walmsleyph** [comment]
Hi Philip,

You could also continue to use Schema Central (the datypic.com link you provided above).  That is HTML generated from the official NIEM XSDs using XSLT.  I have not publicly released the XSLT source code for that, though.

XML Editors (XMLSpy, oXygen) also generate HTML from XSDs but the result tends to be somewhat unwieldy for a large model like NIEM.

**Comment by CB2** [comment]
Hi Philip,
We have quick links to model content on an .io page, https://niem.github.io/model-content/.  Is the NIEM Core (center of picture) hyperlink what you are looking for?
-Christina

**Comment by webb** [comment]
I'm closing this issue. Please let me know if you need more info!
